import 'dart:io';
import 'dart:typed_data';

import 'package:archive/archive.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

import '../codegen/blocks_js_generator.dart';
import '../codegen/css_generator.dart';
import '../codegen/html_generator.dart';
import '../models/project.dart';

/// Builds a static-site ZIP from a [Project] and shares it via the
/// platform share sheet.
class ExportService {
  Future<File> exportZip(Project project) async {
    final archive = Archive();

    // README
    archive.addFile(_textFile('README.md', _readme(project)));

    // Stylesheet
    archive.addFile(
      _textFile('public/assets/css/styles.css', CssGenerator.baseStylesheet()),
    );

    // Generated JS for block-driven event handlers (omitted when empty).
    final js = BlocksJsGenerator.generateProject(project);
    final hasJs = js.trim().isNotEmpty;
    if (hasJs) {
      archive.addFile(_textFile('public/assets/js/main.js', js));
    }

    // Pages
    for (final page in project.pages) {
      final fileName = page.fileName.endsWith('.html')
          ? page.fileName
          : '${page.fileName}.html';
      final html = HtmlGenerator.pageDocument(project, page,
          includeMainScript: hasJs);
      archive.addFile(_textFile('public/$fileName', html));
    }

    // Project source (for re-import later)
    archive.addFile(_textFile(
      'project.webcraft.json',
      _prettyJson(project),
    ));

    final zipBytes = ZipEncoder().encode(archive);
    if (zipBytes == null) {
      throw Exception('Failed to encode ZIP archive');
    }

    final tempDir = await getTemporaryDirectory();
    final safeName = _slug(project.name);
    final outFile = File('${tempDir.path}/$safeName.zip');
    await outFile.writeAsBytes(zipBytes, flush: true);
    return outFile;
  }

  Future<void> shareZip(Project project) async {
    final file = await exportZip(project);
    await Share.shareXFiles(
      [XFile(file.path, mimeType: 'application/zip')],
      subject: '${project.name} (WebCraft project)',
    );
  }

  ArchiveFile _textFile(String path, String content) {
    final bytes = Uint8List.fromList(content.codeUnits);
    return ArchiveFile(path, bytes.length, bytes);
  }

  String _readme(Project project) {
    return '''# ${project.name}

Generated by WebCraft.

## Structure

- `public/` — static site (HTML + CSS). Open `public/index.html` in a browser, or upload the contents to any web host.
- `project.webcraft.json` — re-importable WebCraft project source.

## Pages

${project.pages.map((p) => '- public/${p.fileName}').join('\n')}
''';
  }

  String _prettyJson(Project project) {
    final m = project.toJson();
    return _encodePretty(m);
  }

  String _encodePretty(Object? obj, {int indent = 0}) {
    final pad = '  ' * indent;
    final padInner = '  ' * (indent + 1);
    if (obj is Map) {
      if (obj.isEmpty) return '{}';
      final entries = obj.entries
          .map((e) =>
              '$padInner"${_escape(e.key.toString())}": ${_encodePretty(e.value, indent: indent + 1)}')
          .join(',\n');
      return '{\n$entries\n$pad}';
    }
    if (obj is List) {
      if (obj.isEmpty) return '[]';
      final items = obj
          .map((e) => '$padInner${_encodePretty(e, indent: indent + 1)}')
          .join(',\n');
      return '[\n$items\n$pad]';
    }
    if (obj is num || obj is bool) return obj.toString();
    if (obj == null) return 'null';
    return '"${_escape(obj.toString())}"';
  }

  String _escape(String s) {
    return s
        .replaceAll('\\', r'\\')
        .replaceAll('"', r'\"')
        .replaceAll('\n', r'\n')
        .replaceAll('\r', r'\r')
        .replaceAll('\t', r'\t');
  }

  static String _slug(String name) {
    final s =
        name.trim().toLowerCase().replaceAll(RegExp(r'[^a-z0-9_-]+'), '-');
    final t = s.replaceAll(RegExp(r'(^-+|-+$)'), '');
    return t.isEmpty ? 'webcraft-project' : t;
  }
}
