import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:archive/archive.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

import '../codegen/blocks_js_generator.dart';
import '../codegen/css_generator.dart';
import '../codegen/html_generator.dart';
import '../models/project.dart';

/// Target preset for the export. Most exports go to a generic static host;
/// `githubPages` adds a `.nojekyll` marker and tweaks the README so the
/// project deploys correctly to a `gh-pages`-style branch.
enum ExportTarget { generic, githubPages }

/// Builds a static-site ZIP from a [Project] and shares it via the
/// platform share sheet.
class ExportService {
  Future<File> exportZip(
    Project project, {
    ExportTarget target = ExportTarget.generic,
  }) async {
    final archive = Archive();

    // README — varies slightly by target.
    archive.addFile(_textFile('README.md', _readme(project, target)));

    // Stylesheet — now embeds theme variables and the user's custom CSS.
    archive.addFile(
      _textFile(
          'public/assets/css/styles.css', CssGenerator.stylesheetFor(project)),
    );

    // GitHub Pages: drop the .nojekyll marker so files starting with `_`
    // are served verbatim and Jekyll doesn't reprocess the output.
    if (target == ExportTarget.githubPages) {
      archive.addFile(_textFile('public/.nojekyll', ''));
    }

    // Generated JS for block-driven event handlers (omitted when empty).
    final js = BlocksJsGenerator.generateProject(project);
    final hasJs = js.trim().isNotEmpty;
    if (hasJs) {
      archive.addFile(_textFile('public/assets/js/main.js', js));
    }

    // Pages
    for (final page in project.pages) {
      final fileName = page.fileName.endsWith('.html')
          ? page.fileName
          : '${page.fileName}.html';
      final html = HtmlGenerator.pageDocument(project, page,
          includeMainScript: hasJs);
      archive.addFile(_textFile('public/$fileName', html));
    }

    // Project source (for re-import later)
    archive.addFile(_textFile(
      'project.webcraft.json',
      _prettyJson(project),
    ));

    final zipBytes = ZipEncoder().encode(archive);
    if (zipBytes == null) {
      throw Exception('Failed to encode ZIP archive');
    }

    final tempDir = await getTemporaryDirectory();
    final safeName = _slug(project.name);
    final outFile = File('${tempDir.path}/$safeName.zip');
    await outFile.writeAsBytes(zipBytes, flush: true);
    return outFile;
  }

  Future<void> shareZip(
    Project project, {
    ExportTarget target = ExportTarget.generic,
  }) async {
    final file = await exportZip(project, target: target);
    await Share.shareXFiles(
      [XFile(file.path, mimeType: 'application/zip')],
      subject: '${project.name} (WebCraft project)',
    );
  }

  ArchiveFile _textFile(String path, String content) {
    // Use UTF-8 (not codeUnits which truncates each UTF-16 unit to a byte)
    // so non-ASCII content survives the ZIP round-trip.
    final bytes = Uint8List.fromList(utf8.encode(content));
    return ArchiveFile(path, bytes.length, bytes);
  }

  String _readme(Project project, ExportTarget target) {
    if (target == ExportTarget.githubPages) {
      return '''# ${project.name}

Generated by WebCraft for **GitHub Pages**.

## Deploy

1. Create a new repository (or open an existing one).
2. Copy everything inside `public/` to the repository root (or a `docs/` folder).
3. In the repo Settings → Pages, choose the branch + folder you used.
4. The site will be served from `https://<user>.github.io/<repo>/`.

The `public/.nojekyll` file disables Jekyll processing so any underscore-
prefixed assets are served verbatim.

## Pages

${project.pages.map((p) => '- public/${p.fileName}').join('\n')}
''';
    }
    return '''# ${project.name}

Generated by WebCraft.

## Structure

- `public/` — static site (HTML + CSS). Open `public/index.html` in a browser, or upload the contents to any web host.
- `project.webcraft.json` — re-importable WebCraft project source.

## Pages

${project.pages.map((p) => '- public/${p.fileName}').join('\n')}
''';
  }

  String _prettyJson(Project project) {
    final m = project.toJson();
    return _encodePretty(m);
  }

  String _encodePretty(Object? obj, {int indent = 0}) {
    final pad = '  ' * indent;
    final padInner = '  ' * (indent + 1);
    if (obj is Map) {
      if (obj.isEmpty) return '{}';
      final entries = obj.entries
          .map((e) =>
              '$padInner"${_escape(e.key.toString())}": ${_encodePretty(e.value, indent: indent + 1)}')
          .join(',\n');
      return '{\n$entries\n$pad}';
    }
    if (obj is List) {
      if (obj.isEmpty) return '[]';
      final items = obj
          .map((e) => '$padInner${_encodePretty(e, indent: indent + 1)}')
          .join(',\n');
      return '[\n$items\n$pad]';
    }
    if (obj is num || obj is bool) return obj.toString();
    if (obj == null) return 'null';
    return '"${_escape(obj.toString())}"';
  }

  String _escape(String s) {
    return s
        .replaceAll('\\', r'\\')
        .replaceAll('"', r'\"')
        .replaceAll('\n', r'\n')
        .replaceAll('\r', r'\r')
        .replaceAll('\t', r'\t');
  }

  static String _slug(String name) {
    final s =
        name.trim().toLowerCase().replaceAll(RegExp(r'[^a-z0-9_-]+'), '-');
    final t = s.replaceAll(RegExp(r'(^-+|-+$)'), '');
    return t.isEmpty ? 'webcraft-project' : t;
  }
}
