import '../blocks/catalog/block_registry.dart';
import '../blocks/model/block_node.dart';
import '../blocks/model/block_types.dart';
import '../blocks/model/block_workspace.dart';
import '../models/project.dart';

/// Translates the block workspaces attached to a [Project] into a single
/// `main.js` payload that wires up `window.load`, element click/change/submit
/// handlers and free-floating helpers.
///
/// The generator is deterministic and dependency-free (no Flutter / no I/O)
/// so it can be unit-tested in isolation and shared between the WebView
/// preview path and the ZIP export path.
class BlocksJsGenerator {
  /// Emit the full `main.js` for [project]. Returns an empty string when
  /// the project has no non-empty workspaces.
  static String generateProject(Project project) {
    final entries = project.workspaces.entries
        .where((e) => !e.value.isEmpty)
        .toList(growable: false);
    if (entries.isEmpty) return '';

    final body = StringBuffer();
    var emittedAny = false;
    for (final e in entries) {
      final delta = StringBuffer();
      final wrote = _emitWorkspace(delta, e.key, e.value);
      if (wrote) {
        body.write(delta);
        body.writeln();
        emittedAny = true;
      }
    }
    if (!emittedAny) return '';

    final sb = StringBuffer();
    sb.writeln('// Generated by WebCraft. Do not edit by hand.');
    sb.writeln('(function () {');
    sb.writeln('  "use strict";');
    sb.writeln();
    sb.writeln('  function \$(id) {');
    sb.writeln('    return document.querySelector(\'[data-wc-id="\' + id + \'"]\') || document.getElementById(id);');
    sb.writeln('  }');
    sb.writeln();
    sb.write(body);
    sb.writeln('})();');
    return sb.toString();
  }

  // ---------------------------------------------------------------------------
  // Workspace dispatch
  // ---------------------------------------------------------------------------

  static bool _emitWorkspace(
      StringBuffer sb, String workspaceId, BlockWorkspace ws) {
    final parsed = _WorkspaceKey.parse(workspaceId);
    if (parsed == null) return false;

    BlockNode? hat;
    for (final r in ws.roots) {
      final spec = BlockRegistry.instance.lookup(r.specId);
      if (spec != null && spec.shape == BlockShape.hat) {
        hat = r;
        break;
      }
    }
    if (hat == null) return false;

    final ctx = _Ctx(parsed: parsed);
    final body = _emitChain(hat.next, indent: 2, ctx: ctx);
    final vars = ws.variables
        .map((v) =>
            '    let ${_safeName(v.name)} = ${_jsLiteral(v.defaultValue, v.type)};')
        .join('\n');
    final preamble = vars.isEmpty ? '' : '$vars\n';
    final fullBody = '$preamble$body';

    if (parsed.kind == _WorkspaceKind.page) {
      sb.writeln('  // Page handler: ${parsed.id}/${parsed.event}');
      sb.writeln(
          '  window.addEventListener("DOMContentLoaded", function () {');
      sb.write(fullBody);
      sb.writeln('  });');
      return true;
    }

    final domEvent = _domEventForLogical(parsed.event);
    sb.writeln('  // Element handler: #${parsed.id} on ${parsed.event}');
    sb.writeln('  (function () {');
    sb.writeln('    var __el = \$(${_jsString(parsed.id)});');
    sb.writeln('    if (!__el) return;');
    sb.writeln(
        '    __el.addEventListener(${_jsString(domEvent)}, function (event) {');
    sb.write(fullBody);
    sb.writeln('    });');
    sb.writeln('  })();');
    return true;
  }

  // ---------------------------------------------------------------------------
  // Statement chain
  // ---------------------------------------------------------------------------

  static String _emitChain(BlockNode? head,
      {required int indent, required _Ctx ctx}) {
    if (head == null) return '';
    final sb = StringBuffer();
    BlockNode? cur = head;
    while (cur != null) {
      sb.write(_emitStatement(cur, indent: indent, ctx: ctx));
      cur = cur.next;
    }
    return sb.toString();
  }

  static String _emitStatement(BlockNode node,
      {required int indent, required _Ctx ctx}) {
    final pad = '  ' * indent;
    final spec = BlockRegistry.instance.lookup(node.specId);
    if (spec == null) return '$pad/* unknown spec ${node.specId} */\n';

    switch (node.specId) {
      case 'set_var':
        final name = _safeName(_field(node, 'name', 'tmp'));
        final value = _emitExpr(node.slotChildren['value'], ctx);
        return '$pad$name = $value;\n';

      case 'dom_set_text':
        final target = _targetExpr(node, ctx);
        final value = _emitExpr(node.slotChildren['value'], ctx);
        return '$pad{ var __t = $target; if (__t) __t.textContent = $value; }\n';

      case 'dom_set_style':
        final target = _targetExpr(node, ctx);
        final prop = _field(node, 'prop', 'color');
        final value = _emitExpr(node.slotChildren['value'], ctx);
        return '$pad{ var __s = $target; if (__s) __s.style[${_jsString(_camelize(prop))}] = $value; }\n';

      case 'dom_show_hide':
        final target = _targetExpr(node, ctx);
        final action = _field(node, 'action', 'show');
        final display = action == 'hide' ? '"none"' : '""';
        return '$pad{ var __v = $target; if (__v) __v.style.display = $display; }\n';

      case 'dom_add_class':
        final target = _targetExpr(node, ctx);
        final name = _field(node, 'name', 'active');
        final action = _field(node, 'action', 'add');
        final m = action == 'remove'
            ? 'remove'
            : (action == 'toggle' ? 'toggle' : 'add');
        return '$pad{ var __c = $target; if (__c) __c.classList.$m(${_jsString(name)}); }\n';

      case 'if_else':
        final cond = _emitExpr(node.slotChildren['cond'], ctx);
        final thenStack = node.mouthStacks['then'] ?? const <BlockNode>[];
        final elseStack = node.mouthStacks['else'] ?? const <BlockNode>[];
        final thenBody = _emitMouth(thenStack, indent + 1, ctx);
        final hasElse = elseStack.isNotEmpty;
        final elseBody = _emitMouth(elseStack, indent + 1, ctx);
        final sb = StringBuffer()
          ..write('${pad}if ($cond) {\n')
          ..write(thenBody)
          ..write('$pad}');
        if (hasElse) {
          sb
            ..write(' else {\n')
            ..write(elseBody)
            ..write('$pad}');
        }
        sb.write('\n');
        return sb.toString();

      case 'while_loop':
        final cond = _emitExpr(node.slotChildren['cond'], ctx);
        final body = _emitMouth(
            node.mouthStacks['body'] ?? const [], indent + 1, ctx);
        return '${pad}while ($cond) {\n$body$pad}\n';

      case 'repeat_n':
        final count = _emitExpr(node.slotChildren['count'], ctx);
        final body = _emitMouth(
            node.mouthStacks['body'] ?? const [], indent + 1, ctx);
        return '${pad}for (var __i = 0, __n = ($count); __i < __n; __i++) {\n$body$pad}\n';

      case 'storage_set':
        final key = _field(node, 'key', 'key');
        final value = _emitExpr(node.slotChildren['value'], ctx);
        return '${pad}localStorage.setItem(${_jsString(key)}, String($value));\n';

      case 'list_add':
        final list = _emitExpr(node.slotChildren['list'], ctx);
        final item = _emitExpr(node.slotChildren['item'], ctx);
        return '$pad{ var __l = $list; if (__l && __l.push) __l.push($item); }\n';

      case 'wait_ms':
        final ms = _field(node, 'ms', '500');
        // True async wait inside a sync handler is not yet supported. We emit
        // a setTimeout marker so behaviour at least logs the intent.
        return '$pad/* TODO: wait $ms ms (needs async refactor) */\n';

      case 'http_get':
        // Treated as a fire-and-log statement when on its own. The expression
        // form (used inside a slot) emits a Promise instead.
        final url = _emitExpr(node.slotChildren['url'], ctx);
        return '${pad}fetch($url).then(function (r) { return r.text(); }).then(function (data) { console.log(data); });\n';

      case 'fn_return':
        final value = _emitExpr(node.slotChildren['value'], ctx);
        return '${pad}return $value;\n';

      default:
        return '$pad/* TODO codegen for ${node.specId} */\n';
    }
  }

  static String _emitMouth(List<BlockNode> stack, int indent, _Ctx ctx) {
    if (stack.isEmpty) return '';
    final sb = StringBuffer();
    for (final root in stack) {
      sb.write(_emitChain(root, indent: indent, ctx: ctx));
    }
    return sb.toString();
  }

  // ---------------------------------------------------------------------------
  // Expressions
  // ---------------------------------------------------------------------------

  static String _emitExpr(BlockNode? node, _Ctx ctx) {
    if (node == null) return 'null';
    final spec = BlockRegistry.instance.lookup(node.specId);
    if (spec == null) return 'null /* ${node.specId} */';
    switch (node.specId) {
      case 'number_literal':
        final raw = _field(node, 'value', '0');
        final n = num.tryParse(raw);
        return n == null ? '0' : n.toString();

      case 'text_literal':
        return _jsString(_field(node, 'value', ''));

      case 'get_var':
        return _safeName(_field(node, 'name', 'tmp'));

      case 'math_binop':
        final a = _emitExpr(node.slotChildren['a'], ctx);
        final b = _emitExpr(node.slotChildren['b'], ctx);
        final op = _field(node, 'op', '+');
        final js = switch (op) {
          '×' => '*',
          '÷' => '/',
          _ => op,
        };
        return '($a $js $b)';

      case 'compare':
        final a = _emitExpr(node.slotChildren['a'], ctx);
        final b = _emitExpr(node.slotChildren['b'], ctx);
        final op = _field(node, 'op', '==');
        return '($a $op $b)';

      case 'logic_andor':
        final a = _emitExpr(node.slotChildren['a'], ctx);
        final b = _emitExpr(node.slotChildren['b'], ctx);
        final op =
            _field(node, 'op', 'and') == 'or' ? '||' : '&&';
        return '($a $op $b)';

      case 'logic_not':
        final a = _emitExpr(node.slotChildren['a'], ctx);
        return '(!$a)';

      case 'text_concat':
        final a = _emitExpr(node.slotChildren['a'], ctx);
        final b = _emitExpr(node.slotChildren['b'], ctx);
        return '(String($a) + String($b))';

      case 'text_length':
        final v = _emitExpr(node.slotChildren['s'], ctx);
        return 'String($v).length';

      case 'list_create':
        return '[]';

      case 'list_length':
        final l = _emitExpr(node.slotChildren['list'], ctx);
        return '($l ? $l.length : 0)';

      case 'list_get':
        final l = _emitExpr(node.slotChildren['list'], ctx);
        final i = _emitExpr(node.slotChildren['i'], ctx);
        return '(($l)[$i])';

      case 'dom_get_value':
        final target = _targetExpr(node, ctx);
        // Wrap in an IIFE so the target query runs only once.
        return '(function () { var __g = $target; return __g ? __g.value : ""; })()';

      case 'storage_get':
        final key = _field(node, 'key', 'key');
        return 'localStorage.getItem(${_jsString(key)})';

      case 'http_get':
        // As an expression, return the fetch promise. Code that consumes the
        // value should `.then` on it explicitly.
        final url = _emitExpr(node.slotChildren['url'], ctx);
        return 'fetch($url).then(function (r) { return r.text(); })';

      default:
        return 'null /* expr ${node.specId} */';
    }
  }

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------

  /// Resolve the `target` field of a DOM block. `self` refers to the element
  /// the handler is bound to (or `document.body` for page-level handlers).
  static String _targetExpr(BlockNode node, _Ctx ctx) {
    final raw = _field(node, 'target', 'self').trim();
    if (raw.isEmpty || raw == 'self') {
      return ctx.parsed.kind == _WorkspaceKind.element
          ? '__el'
          : 'document.body';
    }
    return '\$(${_jsString(raw)})';
  }

  static String _field(BlockNode node, String name, String fallback) {
    final v = node.fieldValues[name];
    if (v != null) return v;
    final spec = BlockRegistry.instance.lookup(node.specId);
    final fSpec = spec?.field(name);
    return fSpec?.defaultValue ?? fallback;
  }

  static String _jsString(String s) {
    final escaped = s
        .replaceAll(r'\', r'\\')
        .replaceAll('"', r'\"')
        .replaceAll('\n', r'\n')
        .replaceAll('\r', r'\r')
        .replaceAll('\t', r'\t')
        // Prevent the inline `<script>...</script>` block from being closed
        // early by a user-supplied `</script>` (or any `</...`) literal.
        .replaceAll('</', r'<\/');
    return '"$escaped"';
  }

  static String _jsLiteral(String value, BlockType type) {
    if (value.isEmpty) {
      return switch (type) {
        BlockType.number => '0',
        BlockType.boolean => 'false',
        BlockType.list => '[]',
        BlockType.text => '""',
        _ => 'null',
      };
    }
    if (type == BlockType.number) {
      final n = num.tryParse(value);
      return n == null ? '0' : n.toString();
    }
    if (type == BlockType.boolean) {
      return (value.toLowerCase() == 'true').toString();
    }
    return _jsString(value);
  }

  /// Escape a name so it is a safe JavaScript identifier. Falls back to a
  /// stable hash-based name when the input has nothing usable.
  static String _safeName(String raw) {
    final cleaned = raw.replaceAll(RegExp(r'[^A-Za-z0-9_\$]'), '_');
    if (cleaned.isEmpty) return '_v';
    final firstOk = RegExp(r'[A-Za-z_\$]').hasMatch(cleaned[0]);
    return firstOk ? cleaned : '_$cleaned';
  }

  static String _camelize(String css) {
    final parts = css.split('-');
    if (parts.length <= 1) return css;
    final head = parts.first;
    final tail = parts.skip(1).map(
        (p) => p.isEmpty ? '' : '${p[0].toUpperCase()}${p.substring(1)}');
    return [head, ...tail].join();
  }

  static String _domEventForLogical(String logical) {
    switch (logical) {
      case 'onClick':
        return 'click';
      case 'onChange':
        return 'change';
      case 'onSubmit':
        return 'submit';
      case 'onInput':
        return 'input';
      case 'onFocus':
        return 'focus';
      case 'onBlur':
        return 'blur';
      case 'onMouseEnter':
        return 'mouseenter';
      case 'onMouseLeave':
        return 'mouseleave';
      case 'onLoad':
        return 'load';
      default:
        return logical;
    }
  }
}

enum _WorkspaceKind { page, element }

class _WorkspaceKey {
  _WorkspaceKey(this.kind, this.id, this.event);
  final _WorkspaceKind kind;
  final String id;
  final String event;

  /// Parse `page:<id>:<event>` or `el:<id>:<event>` into structured form.
  static _WorkspaceKey? parse(String raw) {
    final parts = raw.split(':');
    if (parts.length < 3) return null;
    final scope = parts.first;
    final event = parts.last;
    final id = parts.sublist(1, parts.length - 1).join(':');
    switch (scope) {
      case 'page':
        return _WorkspaceKey(_WorkspaceKind.page, id, event);
      case 'el':
        return _WorkspaceKey(_WorkspaceKind.element, id, event);
      default:
        return null;
    }
  }
}

class _Ctx {
  _Ctx({required this.parsed});
  final _WorkspaceKey parsed;
}
