import '../models/element_node.dart';
import '../models/page_node.dart';

/// Pure utility that aggregates per-element and per-page block-generated
/// JavaScript into a single executable script that wires up the page.
class JsGenerator {
  /// Build the contents of `main.js` for [page]. Generated handlers are bound
  /// using `addEventListener` after `DOMContentLoaded` so that the script can
  /// be included anywhere on the page.
  static String pageScript(PageNode page) {
    final buf = StringBuffer();
    buf.writeln('// Auto-generated by WebCraft. Do not edit by hand.');
    buf.writeln('(function () {');
    buf.writeln('  function ready(fn) {');
    buf.writeln("    if (document.readyState !== 'loading') { fn(); }");
    buf.writeln(
        "    else { document.addEventListener('DOMContentLoaded', fn); }");
    buf.writeln('  }');
    buf.writeln('  ready(function () {');

    final onLoad = page.events['onLoad'];
    if (onLoad != null && onLoad.jsBody.trim().isNotEmpty) {
      buf.writeln('    // Page onLoad');
      buf.writeln(_indent(onLoad.jsBody, '    '));
    }

    _walk(page.root, (node) {
      for (final entry in node.events.entries) {
        final js = entry.value.jsBody.trim();
        if (js.isEmpty) continue;
        final selector = _selector(node);
        if (selector == null) continue;
        final domEvent = _toDomEvent(entry.key);
        buf.writeln('    {');
        buf.writeln('      const el = $selector;');
        buf.writeln('      if (el) {');
        buf.writeln(
            '        el.addEventListener(${_q(domEvent)}, function (event) {');
        buf.writeln(_indent(entry.value.jsBody, '          '));
        buf.writeln('        });');
        buf.writeln('      }');
        buf.writeln('    }');
      }
    });

    buf.writeln('  });');
    buf.writeln('})();');
    return buf.toString();
  }

  static void _walk(ElementNode node, void Function(ElementNode) visit) {
    visit(node);
    for (final c in node.children) {
      _walk(c, visit);
    }
  }

  /// Returns a JS expression that resolves to the DOM node for [node].
  /// Prefers an explicit `id` prop, otherwise falls back to a synthetic
  /// `data-wc-id` attribute matching the node's UUID.
  static String? _selector(ElementNode node) {
    final explicitId = (node.props['id'] ?? '').trim();
    if (explicitId.isNotEmpty) {
      return 'document.getElementById(${_q(explicitId)})';
    }
    return 'document.querySelector("[data-wc-id=\'${node.id}\']")';
  }

  static String _toDomEvent(String evt) {
    switch (evt) {
      case 'onClick':
        return 'click';
      case 'onChange':
        return 'change';
      case 'onSubmit':
        return 'submit';
      case 'onInput':
        return 'input';
      case 'onFocus':
        return 'focus';
      case 'onBlur':
        return 'blur';
      default:
        if (evt.startsWith('on')) {
          return evt.substring(2).toLowerCase();
        }
        return evt.toLowerCase();
    }
  }

  static String _q(String s) =>
      '"${s.replaceAll(r'\', r'\\').replaceAll('"', r'\"')}"';

  static String _indent(String body, String prefix) {
    final lines = body.split('\n');
    return lines.map((l) => l.isEmpty ? l : '$prefix$l').join('\n').trimRight();
  }
}
